### ISSUE TITLE
BTC balance not showing after initial sync

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/wallet-web#129]
I fixed a bunch of syncing issues in #128 but when I sync from scratch on my main wallet I see a balance of 0. When I refresh, the balance appears. So it must not be pulling properly after sync.

**Comment by integrate-your-mind** [comment]
This seems to be resolved after last nights fix, as I am now getting the correct balance on logon, each time.

**Comment by alex-miller-0** [comment]
Yeah I haven't been able to replicate. Was probably just stale state.

**Comment by integrate-your-mind** [comment]
I was able to resolve by clearing my cache, tx’s are showing up now, thank you!

Best Wishes and Kind Regards,

Roman Mondello
Software Engineer
617-775-7241
