### ISSUE TITLE
BTC transactions not appearing

### ISSUE THREAD

**Issue by integrate-your-mind** [GridPlus/wallet-web#131]
For some reason, no past BTC transactions are not appearing on initial logon or after sync.

I have tried clearing the cache, logging out, logging back in, with no luck of seeing the tx's.

<img width="1567" alt="Screen Shot 2021-03-14 at 10 43 43 AM" src="https://user-images.githubusercontent.com/43152353/111072715-27b2b380-84b2-11eb-82a5-33e6325fc42a.png">

**Comment by integrate-your-mind** [comment]
Resolved, had to clear cache, and now tx's are appearing as normal.

**Comment by integrate-your-mind** [comment]
Nope, nevermind, tx's are appearing then disappearing after initial load, even after clearing cache, seems to be on first sync.

**Comment by alex-miller-0** [comment]
This should be solved now. Let us know if you're still having issues.
