### ISSUE TITLE
"Retry" doesn't retry

### ISSUE THREAD

**Issue by KevinVitale** [GridPlus/wallet-web#179]
## Description 
If connecting times out (because the device is unplugged, for example), and you hit the "Retry" button (because the device has since been plugged back in), then the user is told the password needs to be at least 8 characters.

## Expected Behavior

Pressing "Retry" should retry to connect to the device with existing `deviceID` and `password`.

<img width="573" alt="Screen Shot 2021-11-18 at 6 37 27 PM" src="https://user-images.githubusercontent.com/276137/142513807-7bfb86c6-6bb0-4fdc-93f2-378e5d55574d.png">
<img width="573" alt="Screen Shot 2021-11-18 at 6 37 33 PM" src="https://user-images.githubusercontent.com/276137/142513810-1e78fb06-fce3-4513-a3f3-d131b52ca5bc.png">

**Comment by alex-miller-0** [comment]
Oh yeah. I noticed this earlier in a different component actually. Will go through and hook everything up
